"""Response schemas for the chatbot endpoint."""

from typing import List, Optional
from pydantic import BaseModel, Field


class AskResponse(BaseModel):
    """Payload returned by POST /ask."""

    answer: str = Field(
        ...,
        description="The natural language answer generated by the hosted LLM.",
    )
    sources: List[str] = Field(
        ...,
        description="Explicit list of sources from which information was retrieved.",
        examples=[["Superhero API (Batman)"], ["Text Dataset (thor_norse_mythology.txt)"]],
    )
    route: str = Field(
        ...,
        description="The source category determined by the router: 'dataset', 'superhero', or 'both'.",
    )
    retrieved_superheroes: Optional[List[str]] = Field(
        default=None,
        description="Names of superheroes retrieved from the Superhero API, if applicable.",
    )
    retrieved_documents: Optional[List[str]] = Field(
        default=None,
        description="Titles or filenames of documents retrieved from the text dataset, if applicable.",
    )
    latency_ms: Optional[float] = Field(
        default=None,
        description="Total round-trip processing time in milliseconds.",
    )
    llm_provider: Optional[str] = Field(
        default=None,
        description="The hosted LLM provider that generated the response.",
    )
